### ISSUE TITLE
Typo (showing atom as uatom)

### ISSUE THREAD

**Issue by terencesflam** [forbole/big_dipper#279] opened 2020-02-11 13:12 UTC
**Describe the bug**

The "uatom" circled in below screen should be "atom"

![Screenshot 2020-02-11 at 9 10 00 PM](https://user-images.githubusercontent.com/34306139/74239592-1cbbab80-4d13-11ea-9bfa-d15ea6c9c575.png

**Comment by kwunyeung** [comment] 2020-02-11 15:10
Duplicate of #260 and PR #266 is ready to be merged.

**Closed by kwunyeung** 2020-02-11 15:10 UTC
Labels: duplicate
