### ISSUE TITLE
Account details should keep refreshing

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big_dipper#143] opened 2019-07-03 09:03 UTC
The account page https://cosmos.bigdipper.live/account/cosmos14kn0kk33szpwus9nh8n87fjel8djx0y0mmswhp should keep refreshing, for example, every 10 seconds. Then the frontend will show the latest values of the account after gaining more rewards or after transactions.

**Comment by ztsai** [comment] 2019-07-25 08:33
duplicate of #95

**Closed by ztsai** 2019-07-25 08:33 UTC
Labels: enhancement, ux
